{-# LANGUAGE CPP #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif
{-# LANGUAGE FlexibleInstances #-}
{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}

-- | Pretty-printer for Grammar.
--   Generated by the BNF converter.

module Grammar.Print where

import qualified Grammar.Abs
import Data.Char

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : ts@(p:_) | closingOrPunctuation p -> showString t . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else ' ':s)

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Grammar.Abs.Ident where
  prt _ (Grammar.Abs.Ident i) = doc (showString i)

instance Print Grammar.Abs.Program where
  prt i e = case e of
    Grammar.Abs.Prog decls -> prPrec i 0 (concatD [prt 0 decls])

instance Print [Grammar.Abs.Decl] where
  prt = prtList

instance Print Grammar.Abs.Decl where
  prt i e = case e of
    Grammar.Abs.VarDecl type_ id -> prPrec i 0 (concatD [prt 0 type_, prt 0 id, doc (showString ";")])
    Grammar.Abs.VarDeclAss type_ id expr -> prPrec i 0 (concatD [prt 0 type_, prt 0 id, doc (showString "="), prt 0 expr, doc (showString ";")])
    Grammar.Abs.FnDecl type_ id args block -> prPrec i 0 (concatD [prt 0 type_, prt 0 id, doc (showString "("), prt 0 args, doc (showString ")"), prt 0 block])
  prtList _ [] = concatD []
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print Grammar.Abs.Arg where
  prt i e = case e of
    Grammar.Abs.ValArg type_ id -> prPrec i 0 (concatD [prt 0 type_, prt 0 id])
    Grammar.Abs.RefArg type_ id -> prPrec i 0 (concatD [prt 0 type_, doc (showString "&"), prt 0 id])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [Grammar.Abs.Arg] where
  prt = prtList

instance Print Grammar.Abs.Block where
  prt i e = case e of
    Grammar.Abs.Blk stmts -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stmts, doc (showString "}")])

instance Print [Grammar.Abs.Stmt] where
  prt = prtList

instance Print Grammar.Abs.Stmt where
  prt i e = case e of
    Grammar.Abs.Empty -> prPrec i 0 (concatD [doc (showString ";")])
    Grammar.Abs.BStmt block -> prPrec i 0 (concatD [prt 0 block])
    Grammar.Abs.DStmt decl -> prPrec i 0 (concatD [prt 0 decl])
    Grammar.Abs.Ass id expr -> prPrec i 0 (concatD [prt 0 id, doc (showString "="), prt 0 expr, doc (showString ";")])
    Grammar.Abs.Ret expr -> prPrec i 0 (concatD [doc (showString "return"), prt 0 expr, doc (showString ";")])
    Grammar.Abs.VRet -> prPrec i 0 (concatD [doc (showString "return"), doc (showString ";")])
    Grammar.Abs.Cond expr block -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 block])
    Grammar.Abs.CondElse expr block1 block2 -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 block1, doc (showString "else"), prt 0 block2])
    Grammar.Abs.While expr block -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 block])
    Grammar.Abs.Break -> prPrec i 0 (concatD [doc (showString "break")])
    Grammar.Abs.Continue -> prPrec i 0 (concatD [doc (showString "continue")])
    Grammar.Abs.SExp expr -> prPrec i 0 (concatD [prt 0 expr, doc (showString ";")])
    Grammar.Abs.Print expr -> prPrec i 0 (concatD [doc (showString "print"), doc (showString "("), prt 0 expr, doc (showString ")")])
  prtList _ [] = concatD []
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print Grammar.Abs.Type where
  prt i e = case e of
    Grammar.Abs.Int -> prPrec i 0 (concatD [doc (showString "int")])
    Grammar.Abs.Str -> prPrec i 0 (concatD [doc (showString "string")])
    Grammar.Abs.Bool -> prPrec i 0 (concatD [doc (showString "boolean")])
    Grammar.Abs.Void -> prPrec i 0 (concatD [doc (showString "void")])

instance Print Grammar.Abs.Expr where
  prt i e = case e of
    Grammar.Abs.EVar id -> prPrec i 6 (concatD [prt 0 id])
    Grammar.Abs.ELitInt n -> prPrec i 6 (concatD [prt 0 n])
    Grammar.Abs.ELitTrue -> prPrec i 6 (concatD [doc (showString "true")])
    Grammar.Abs.ELitFalse -> prPrec i 6 (concatD [doc (showString "false")])
    Grammar.Abs.EApp id exprs -> prPrec i 6 (concatD [prt 0 id, doc (showString "("), prt 0 exprs, doc (showString ")")])
    Grammar.Abs.EString str -> prPrec i 6 (concatD [prt 0 str])
    Grammar.Abs.Neg expr -> prPrec i 5 (concatD [doc (showString "-"), prt 6 expr])
    Grammar.Abs.Not expr -> prPrec i 5 (concatD [doc (showString "!"), prt 6 expr])
    Grammar.Abs.EMul expr1 mulop expr2 -> prPrec i 4 (concatD [prt 4 expr1, prt 0 mulop, prt 5 expr2])
    Grammar.Abs.EAdd expr1 addop expr2 -> prPrec i 3 (concatD [prt 3 expr1, prt 0 addop, prt 4 expr2])
    Grammar.Abs.ERel expr1 relop expr2 -> prPrec i 2 (concatD [prt 2 expr1, prt 0 relop, prt 3 expr2])
    Grammar.Abs.EAnd expr1 expr2 -> prPrec i 1 (concatD [prt 2 expr1, doc (showString "&&"), prt 1 expr2])
    Grammar.Abs.EOr expr1 expr2 -> prPrec i 0 (concatD [prt 1 expr1, doc (showString "||"), prt 0 expr2])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [Grammar.Abs.Expr] where
  prt = prtList

instance Print Grammar.Abs.AddOp where
  prt i e = case e of
    Grammar.Abs.Plus -> prPrec i 0 (concatD [doc (showString "+")])
    Grammar.Abs.Minus -> prPrec i 0 (concatD [doc (showString "-")])

instance Print Grammar.Abs.MulOp where
  prt i e = case e of
    Grammar.Abs.Times -> prPrec i 0 (concatD [doc (showString "*")])
    Grammar.Abs.Div -> prPrec i 0 (concatD [doc (showString "/")])
    Grammar.Abs.Mod -> prPrec i 0 (concatD [doc (showString "%")])

instance Print Grammar.Abs.RelOp where
  prt i e = case e of
    Grammar.Abs.LTH -> prPrec i 0 (concatD [doc (showString "<")])
    Grammar.Abs.LE -> prPrec i 0 (concatD [doc (showString "<=")])
    Grammar.Abs.GTH -> prPrec i 0 (concatD [doc (showString ">")])
    Grammar.Abs.GE -> prPrec i 0 (concatD [doc (showString ">=")])
    Grammar.Abs.EQU -> prPrec i 0 (concatD [doc (showString "==")])
    Grammar.Abs.NE -> prPrec i 0 (concatD [doc (showString "!=")])

